version: 2.1
orbs:
  gradle: circleci/gradle@1.0.10
  win: circleci/windows@5.0
_defaults: &defaults
  working_directory: ~/code
  environment:
    JVM_OPTS: -Xmx3200m
_gradle_checksum: &gradle_checksum
  name: Generate Cache Checksum
  command: >-
    find . -name 'build.gradle' | sort | xargs cat | shasum | awk '{print
    $1}' > /tmp/gradle_cache_seed
jobs:
  build-linux:
    docker:
      - image: cimg/openjdk:16.0.2-browsers
    resource_class: medium # TODO: revert prior to upstream PR
    <<: *defaults
    steps:
      - checkout
      # We can't use gradle/with_cache because it does not include the .konan dir where there kotlin native compiler lives
      - run:
          <<: *gradle_checksum
      - restore_cache:
          key: >-
            gradle-{{ checksum "/tmp/gradle_cache_seed" }}-{{ checksum
            ".circleci/config.yml" }}-linux
      - run:
          name: Build
          command: ./gradlew build
      - gradle/collect_test_results:
          test_results_path: build/test-results
          reports_path: build/reports
      - deploy:
          command: |
            if [ "${CIRCLE_BRANCH}" == "main" ]; then
              echo "$MAVEN_CENTRAL_SEC_RING" | base64 -d > $HOME/secring.gpg
              gpg --import --batch $HOME/secring.gpg
              ./gradlew dokkaJavadocCommonJar
              ./gradlew publish -PsonatypeUsername="$SONATYPE_USERNAME" -PsonatypePassword="$SONATYPE_PASSWORD" -Psigning.keyId="$MAVEN_CENTRAL_KEY_ID" -Psigning.password="$MAVEN_CENTRAL_KEY_PASSPHRASE" -Psigning.secretKeyRingFile=$HOME/secring.gpg --no-parallel
            fi
      - save_cache:
          paths:
            - ~/.gradle/caches
            - ~/.gradle/wrapper
            - ~/.konan
          key: >-
            gradle-{{ checksum "/tmp/gradle_cache_seed" }}-{{ checksum
            ".circleci/config.yml" }}-linux
  build-macos:
    macos:
      xcode: "14.1.0"
    resource_class: macos.x86.medium.gen2
    <<: *defaults
    steps:
      - checkout
      # We can't use gradle/with_cache because it incorrectly uses the same cache key from build-linux
      - run:
          <<: *gradle_checksum
      - restore_cache:
          key: >-
            gradle-{{ checksum "/tmp/gradle_cache_seed" }}-{{ checksum
            ".circleci/config.yml" }}-macos
      - run:
          name: Build Apple
          command: ./gradlew buildApple
      - deploy:
          command: |
            if [ "${CIRCLE_BRANCH}" == "main" ]; then
              echo "$MAVEN_CENTRAL_SEC_RING" | base64 -D -o $HOME/secring.gpg
              ./gradlew dokkaJavadocCommonJar
              ./gradlew publishApple -PsonatypeUsername="$SONATYPE_USERNAME" -PsonatypePassword="$SONATYPE_PASSWORD" -Psigning.keyId="$MAVEN_CENTRAL_KEY_ID" -Psigning.password="$MAVEN_CENTRAL_KEY_PASSPHRASE" -Psigning.secretKeyRingFile=$HOME/secring.gpg --no-parallel
            fi
      - save_cache:
          paths:
            - ~/.gradle/caches
            - ~/.gradle/wrapper
            - ~/.konan
          key: >-
            gradle-{{ checksum "/tmp/gradle_cache_seed" }}-{{ checksum
            ".circleci/config.yml" }}-macos
  build-windows:
    executor: win/default
    steps:
      - checkout
      # TODO: restore cache on windows
      - run:
          command: gradlew.bat build
          shell: cmd.exe
      # TODO: save cache on windows
workflows:
  version: 2
  build:
    jobs:
      - build-linux:
          filters:
            branches:
              ignore: main
      - build-macos:
          filters:
            branches:
              ignore: main
      - build-windows:
          filters:
            branches:
              ignore: main
      - build-linux:
          context: opensource-maven
          filters:
            branches:
              only: main
      - build-macos:
          context: opensource-maven
          filters:
            branches:
              only: main